# Generated by Django 5.2.13 on 2026-04-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(db_index=True, max_length=100)),
                ('article_number', models.CharField(max_length=50)),
                ('article_title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='쉼표로 구분된 검색 키워드', max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laws', to='stories.category')),
            ],
            options={
                'verbose_name': '법령',
                'verbose_name_plural': '법령',
                'ordering': ['law_name', 'article_number'],
            },
        ),
        migrations.CreateModel(
            name='Precedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=100)),
                ('case_name', models.CharField(max_length=300)),
                ('court', models.CharField(db_index=True, max_length=100)),
                ('judgment_date', models.DateField(db_index=True)),
                ('summary', models.TextField(help_text='판결 요지')),
                ('content', models.TextField(help_text='판례 본문 또는 발췌')),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('result_type', models.CharField(choices=[('plaintiff_win', '원고승'), ('plaintiff_partial', '원고일부승'), ('defendant_win', '원고패'), ('settled', '조정/화해'), ('etc', '기타')], default='etc', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedents', to='stories.category')),
                ('related_laws', models.ManyToManyField(blank=True, related_name='precedents', to='legal_data.law')),
            ],
            options={
                'verbose_name': '판례',
                'verbose_name_plural': '판례',
                'ordering': ['-judgment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='law',
            index=models.Index(fields=['law_name'], name='legal_data__law_nam_f0f961_idx'),
        ),
        migrations.AddIndex(
            model_name='law',
            index=models.Index(fields=['category'], name='legal_data__categor_fd799f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='law',
            unique_together={('law_name', 'article_number')},
        ),
        migrations.AddIndex(
            model_name='precedent',
            index=models.Index(fields=['court', '-judgment_date'], name='legal_data__court_132eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='precedent',
            index=models.Index(fields=['category'], name='legal_data__categor_05f64c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precedent',
            unique_together={('case_number', 'court')},
        ),
    ]
