# Generated by Django 5.2.13 on 2026-05-04 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('author', '작성자 본인 삭제'), ('report', '신고 누적 자동 삭제'), ('admin', '관리자 수동 삭제')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '스팸/광고'), ('abuse', '욕설/비방'), ('misinfo', '허위정보'), ('obscene', '음란/혐오'), ('etc', '기타')], default='etc', max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='interactions.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고',
                'indexes': [models.Index(fields=['comment', 'created_at'], name='interaction_comment_bac703_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
