# Generated by Django 5.2.13 on 2026-05-04 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('keywords', models.CharField(blank=True, default='', help_text='extract_keywords 적용 결과 (조사 stripping 후), 쉼표 구분', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='비로그인 사용자도 기록 (null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검색 로그',
                'verbose_name_plural': '검색 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='search_sear_query_62def4_idx'), models.Index(fields=['created_at'], name='search_sear_created_819524_idx')],
            },
        ),
    ]
